### ISSUE TITLE
examples for software design courses

### ISSUE THREAD

**Issue by gabriel-fallen** [max-talanov/1#8]
Examples of requirements documents are needed. At least example of vision document.
Some famous vision documents like vision of iPhone by Jobs might be great examples.

**Comment by max-talanov** [comment]
rofl.

Please see approximate contents of the Vision:
https://github.com/max-talanov/1/blob/master/software%20design%20courses/requirements.md#vision

**Comment by gabriel-fallen** [comment]
That wasn't exceptionally nice or explanatory.
Why do you think this issue is irrelevant?

On Mon, Jan 5, 2015 at 5:16 PM, Max Talanov <notifications@github.com>
wrote:

> Closed #8 <https://github.com/max-talanov/1/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/max-talanov/1/issues/8#event-214085652>.
>



-- 
С уважением,
Александр.

**Comment by max-talanov** [comment]
Well.
I don't think that one could use iPhone Vision for anything else but the iPhone requirements.
We have to produce proper visions based on current project requirements.
So please use your imagination and try to create the document based on the plan I have provided.
From the other hand: creation of the requirements is job of analyst or product owner not the developer or architect.
This way you have to put yourself on the position of the customer/analyst and create requirements based on business context of future application and this is not feeling the gaps work this is creative work that requires a lot of effort and mastery.

**Comment by gabriel-fallen** [comment]
You're obviously right, but my point was a bit different.

I've missed the issue that this course is for developers/architects and
looked from business/systems analyst perspective so I agree this might be
irrelevant.

Obviously requirements are unique for every project, but to me examples
help distinguish good ones from pure ones. Being guided only by plan you
provided one might came up with complete crap due to lack of experience.
Examples of good views/requirements help get the idea of what is relevant
and helpful and what's not.

At least this is how I see the issue.


On Tue, Jan 6, 2015 at 11:11 AM, Max Talanov <notifications@github.com>
wrote:

> Well.
> I don't think that one could use iPhone Vision for anything else but the
> iPhone requirements.
> We have to produce proper visions based on current project requirements.
> So please use your imagination and try to create the document based on the
> plan I have provided.
> From the other hand: creation of the requirements is job of analyst or
> product owner not the developer or architect.
> This way you have to put yourself on the position of the customer/analyst
> and create requirements based on business context of future application and
> this is not feeling the gaps work this is creative work that requires a lot
> of effort and mastery.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/max-talanov/1/issues/8#issuecomment-68837328>.
>



-- 
С уважением,
Александр.
